allEssays() {
      return [{
        title: 'European Maps for Exploration and Discovery',
        author: 'David Buisseret',
        desc: 'The relationship between discovery/exploration and cartography is also hard to pin down. For many years, it was taken for granted in Western literature that explorers from Western Europe used maps both to...',
        gallery: [],
        url: 'european-maps-exploration-and-discovery',
      },
      {
        title: 'Lines that Fracture and Fade: Two Centuries of Travel through Georgia, 1775-1976',
        author: 'Robert Paulett',
        desc: 'It is perhaps a problem with maps that, for objects so closely associated with human movement, they provide only a limited sense of movement themselves. They mark former movement, certainly, and they propose... ',
        gallery: [],
        url: 'lines-fracture-and-fade-two-centuries-travel-through-georgia-1775-1976',
      },
      {
        title: 'Maps of Trails and Roads of the Great West',
        author: 'Dennis Reinhartz',
        desc: 'The earliest trails of the Great West of North America were those blazed by Indians, and many of them, such as the Comanche Trail across Texas and New Mexico, followed the even older seasonal... ',
        gallery: [],
        url: 'maps-trails-and-roads-great-west',
      },
      {
        title: 'Navigating the Coasts and Seas',
        author: 'John Cloud',
        desc: 'The very essence of coast-wise and maritime navigation is evoked in the engraved plate of a volcano with an oared boat and... ',
        gallery: [],
        url: 'navigating-coasts-and-seas',
      },
      {
        title: "Waterways Cartography, Part I: The Mapping of North America's Internal Navigation Systems",
        author: 'Gerald A. Danzer',
        desc: 'Mapping movement over water, particularly the transport of goods and passengers by way of rivers, lakes, canals, and intracoastal waterways, is an integral part in the story of the development of North America. Our focus here is on how waterways... ',
        gallery: [],
        url: 'waterways-cartography-part-i-mapping-north-americas-internal-navigation-systems',
      },
      {
        title: 'Waterways Cartography, Part II: Landmarks and Exemplars in North America',
        author: 'Gerald A. Danzer',
        desc: '“No part of the world is so well watered as the territories of the United States.” These words of John Phillips in the fourth edition of his General History of Inland Navigation (1803) broadcast what was both a boon and a... ',
        gallery: [],
        url: 'waterways-cartography-part-ii-landmarks-and-exemplars-north-america',
      },
      {
        title: 'Mapping Migration and Settlement',
        author: 'Ronald Grim',
        desc: 'Migration, which is the process of people moving from one place to another in order to establish a new residence, has been a reoccurring theme in US history. The nature of this migration experience has a variety of temporal and geographical... ',
        gallery: [],
        url: 'mapping-migration-and-settlement',
      },
      {
        title: 'Mapping Communication',
        author: 'Robert Macdougall',
        desc: 'Human beings have always communicated—our ancestors communicated before they were technically human beings—yet the concept of “communication,” as we understand it today, is remarkably recent in origin. It was only in the... ',
        gallery: [],
        url: 'mapping-communication',
      },
      {
        title: 'Around, Over, and Through the Americas',
        author: 'Jordana Dym',
        desc: 'In 1922, Berkeley student Frances Toor dedicated her MA thesis on the Moquí people of Spanish New Mexico to Professor Herbert Eugene Bolton for “introducing me to the interesting study of Spanish documents, [which] opened for me new... ',
        gallery: [],
        url: 'around-over-and-through-americas',
      },
      {
        title: 'State and Federal Mapping of Infrastructure and Movement',
        author: 'Susan Schulten',
        desc: 'From the 1790s forward, the United States Government’s role in mapping movement extended across several areas of life, including reconnaissance and exploration, internal improvements and infrastructure, national defense, and overseas... ',
        gallery: [],
        url: 'state-and-federal-mapping-infrastructure-and-movement',
      },
      {
        title: 'Planning Transportation',
        author: 'Joseph P. Schwieterman',
        desc: 'Most of the maps we use in everyday life are designed to make complex transportation systems seem simple. Highway maps often omit railroad lines that are vital for industry but are not as important to passenger travel. Toll-road maps regularly... ',
        gallery: [],
        url: 'planning-transportation',
      },
      {
        title: 'American Railroad Maps, 1828-1876',
        author: 'Gerald A. Danzer with James R. Akerman',
        desc: 'Nineteenth-century railroad maps occupy a pivotal, transformative place in the history of North American transportation and travel cartography, not unlike the railroads they mapped. Railroads enjoyed an outsized place in the history and mythology... ',
        gallery: [],
        url: 'american-railroad-maps-1828-1876',
      },
      {
        title: 'American Railroad Maps, 1873-2012',
        author: 'Gerald A. Danzer',
        desc: 'Henry Varnum Poor’s Manual of the Railroads of the United States for 1874-75 (New York 1874), then in its seventh edition and totaling 945 pages, had become the standard source of information on all railroads of the nation. Of the... ',
        gallery: [],
        url: 'american-railroad-maps-1873-2012',
      },
      {
        title: 'Maps, Movement, and American Literature',
        author: 'Martin Brückner',
        desc: 'Mapping movement is a central theme in the texts of canonical as well as lesser known works taught today in classes on “American Literature.” From Christopher Columbus’s letters reporting on his first voyage (1493) to William... ',
        gallery: [],
        url: 'maps-movement-and-american-literature',
      },
      {
        title: 'Moving Pictures: Maps and Imagination in Eighteenth-Century Anglo-America',
        author: 'Robert Paulett',
        desc: 'In March 1775, William Mylne packed his bags and headed north. A Scottish engineer whose bridges had a bad habit of falling down, Mylne tried to start over as a farmer in Georgia only to fail at that as well. ',
        gallery: [],
        url: 'moving-pictures-maps-and-imagination-eighteenth-century-anglo-america',
      }]
    },Í